name: PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Folder setup
        run: mkdir template

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: template
      
      - name: Install TeX Live
        uses: ryz3d/install-texlive@v1
        with:
          package_file: packages_list.txt
      
      - name: Compile examples
        run: cd template; for i in example_*.tex; do pdflatex $i; done
      
      - name: Biber
        run: cd template; for i in example_*.tex; do biber $i; done
      
      - name: LaTeX compilation Part two
        run: cd template; for i in example_*.tex; do pdflatex $i; done
      
      - name: Archive .pdf
        uses: actions/upload-artifact@v3
        with:
          name: CD_${{github.run_number}}
          path: template/example_*.pdf
