# TODO:
# Package babel Warning: No hyphenation patterns were preloaded for the language 'German (new orthography)' into the format.
# (babel) Please, configure your TeX system to add them and rebuild the format. Now I will use the patterns preloaded for \language=0 instead on input line 48.
# Package tocloft Warning: \@starttoc has already been redefined; tocloft bailing out. on input line 1156.
# Package datetime2 Warning: Date-Time Language Module `ngerman' not installed on input line 1913.

name: PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Folder setup
        run: mkdir template

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: template
      
      - name: Install TeX Live
        uses: ryz3d/install-texlive@v2
        with:
          package_file: template/packages_list.txt
      
      - name: Compile examples
        run: cd template; for i in example_*.tex; do pdflatex $i; done
      
      - name: Biber
        run: cd template; for i in example_*.bcf; do biber $i; done
      
      - name: LaTeX compilation Part two
        run: cd template; for i in example_*.tex; do pdflatex $i; done
      
      - name: Archive .pdf
        uses: actions/upload-artifact@v4
        with:
          name: CD_${{github.run_number}}
          path: template/example_*.pdf
